# Ingestion Config: SAD (Solution Architecture Definition)

collection_name: "fa_ea_sad"

# Documents to ingest
file_paths:
  - "~/Documents/__data/books/SAD.pdf"

# Metadata to attach to all documents
metadata:
  domain: "architecture"
  type: "enterprise architecure"
  source: "SAD"

# Whether to rebuild the collection on each run
rebuild: true
